defaults:
  - _self_
  - task: pt

# Experiment args
mode: 'pt'
device: gpu
eval_only: false
predict_only: false
split_size: 2048
seed: 2137

model:
  name: 'google/t5-v1_1-base'
  checkpoint_path: ''
  dropout: 0.1
  d_ff: 3072
  random_init: true
  compile: false # Pytorch 2.0
  use_morphpiece: false
  use_gpt2: false
  gradient_checkpointing: true

data:
  max_train_samples: 1000
  input_length: 512
  mlm_probability: 0.15
  mean_noise_span_length: 3.0
  num_workers: 8
  streaming: true

optim:
  name: adamwscale
  base_lr: 1e-3
  batch_size: 400
  total_steps: 100000
  epochs: -1 # If it's > 0 it overwrites total_steps
  warmup_steps: 2000
  lr_scheduler: onecycle
  weight_decay: 0.0
  grad_clip: 1.0
  grad_acc: 1
  final_cosine: 1e-5
  mixed_precision: 'fp16'
  deepspeed_plugin: no

eval:
  every_steps: 5000
  steps: 100

checkpoint:
  every_steps: 1000

logging:
  neptune: true
  neptune_creds:
    project: maveriq/MorphT5
    api_token: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI5MWZhOGUxZC0xMTVhLTRjMTEtYjYxMi1mZTU3Y2Y1NTQwZjYifQ=="
    tags: morph,bs456,compiled
  every_steps: 50
  grad_l2: true
  weights_l2: true

hydra:
  job:
    chdir: True
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
